### ISSUE TITLE
np.histogramdd is called with wrong ranges

### ISSUE THREAD

**Issue by njb14163** [UKFELs/Paraffin#5]
When I run the **_fullConv.py_** for my input file it crashes and I had to change this line to work:

**/paraffin/upsample/utilities.py:118**
`Hz, edges_Z = np.histogramdd(z, bins = bnz,range=((zst,zed),(zst,zed)),normed=False,weights=wghts)`
to
`Hz, edges_Z = np.histogramdd(z, bins = bnz,range=((zst,zed)),normed=False,weights=wghts)`

because the data is 1D and **_histogramdd_** function do not accept more ranges.

Please update the code to be compatible with Python2.7

**Comment by piotrt75** [comment]
Please provide details of you system (OS type and version, Python version, numpy version).

**Comment by piotrt75** [comment]
> 
> 
> When I run the **_fullConv.py_** for my input file it crashes and I had to change this line to work:
> 
> **/paraffin/upsample/utilities.py:118**
> `Hz, edges_Z = np.histogramdd(z, bins = bnz,range=((zst,zed),(zst,zed)),normed=False,weights=wghts)`
> to
> `Hz, edges_Z = np.histogramdd(z, bins = bnz,range=((zst,zed)),normed=False,weights=wghts)`
> 
> because the data is 1D and **_histogramdd_** function do not accept more ranges.
> 
> Please update the code to be compatible with Python2.7

Please provide details of you system (OS type and version, Python version, numpy version).

**Comment by njb14163** [comment]
My OS Information:
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"

My Python and Numpy Versions:
Python 2.7.15 :: Anaconda, Inc.
numpy Version: 1.15.1

Your help is highly appreciated. I want to make sure this change is correct and did not affect the final results.

**Comment by piotrt75** [comment]
Issue fixed (details in the GitHub log).
